version: 0.2

env:
  variables:
    # Define your standard environment variables here
    ENV_NAME: "dev"
    NODE_ENV: "development"

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '**/*'
    - 'node_modules/**/*'

reports:
  test-report:
    files:
      - 'coverage/cobertura-coverage.xml'
    file-format: 'COBERTURAXML'
